### ISSUE TITLE
bam logs console applications in win 11?

### ISSUE THREAD

**Issue by lolzz1234** [Psmths/windows-forensic-artifacts#2]
Seems like bam does log the execution of console applications in windows 11, even when it is run through a commandline like cmd.exe

**Comment by Psmths** [comment]
Thank you for bringing this to my attention, will test and update accordingly

**Comment by lolzz1234** [comment]
Sounds good. BTW are you aware of any other methods of file execution that dont leave traces in BAM/DAM?

**Comment by Psmths** [comment]
> Sounds good. BTW are you aware of any other methods of file execution that dont leave traces in BAM/DAM?

I am not aware of a specific file execution method that would not create BAM entries, though I do know that executing an application located on a network share will bypass it. You'd probably have to look into the kernel driver responsible for maintaining BAM entries, `C:\Windows\System32\drivers\bam.sys`.

**Comment by Psmths** [comment]
Updated information in commit [b0faf65](https://github.com/Psmths/windows-forensic-artifacts/commit/b0faf656761091e165b1c4fff74541ebeb29d306)
